// ASYNC
export const ASYNC_ACTION_START = "ASYNC_ACTION_START";
export const ASYNC_ACTION_FINISHED = "ASYNC_ACTION_FINISHED";
export const ASYNC_ACTION_ERROR = "ASYNC_ACTION_ERROR";

// AUTH
export const CHECK_USER_AUTH_STATE = "CHECK_USER_AUTH_STATE";
export const LOGIN_USER = "LOGIN_USER";
export const REGISTER_USER = "REGISTER_USER";
export const LOGOUT_USER = "LOGOUT_USER";

// USER
export const GET_USER = "GET_USER";
export const EDIT_USER = "EDIT_USER";
export const DESTROY_USER = "DESTROY_USER";
